// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBfoHFu4t7ynblK9k78ZS4hSTjmGB8cxk',
    appId: '1:53497997749:web:1fb33e62ca836be39451fc',
    messagingSenderId: '53497997749',
    projectId: 'izzybd-e8a25',
    authDomain: 'izzybd-e8a25.firebaseapp.com',
    storageBucket: 'izzybd-e8a25.appspot.com',
    measurementId: 'G-05HNCC2L77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoKkAC6i0K9eDtKrfrRT7vYZZxaV5mcLU',
    appId: '1:53497997749:android:9998f316850fd1f09451fc',
    messagingSenderId: '53497997749',
    projectId: 'izzybd-e8a25',
    storageBucket: 'izzybd-e8a25.appspot.com',
  );
}
